### ISSUE TITLE
Converting a replay crashes the game

### ISSUE THREAD

**Issue by daniel-dara** [Atomus48/JumpInReplay#1]
I followed the instructions [here](https://bakkesplugins.com/plugins/view/322) for using this plugin on a replay. When doing step 5, "press the convert Replay button", the game will crash. The game also crashes if I check the "Automaticlly convert replays" button.

**Comment by Atomus48** [comment]
do you by any chance have any other plugins enabled that do something in replays?

**Comment by daniel-dara** [comment]
I'm using a few other plugins. They aren't specific to replays but a few of them are active during replays. I'll try disabling all other plugins and give it another try.

**Comment by Al12rs** [comment]
I'm also experiencing the same issue, are there any logs I can take a look at? 
I tried disabling all the plugins that could be related to replays with no success.

**Comment by Al12rs** [comment]
I have found that the incompatible plugin seems to be "True Ball Height Indicator" https://bakkesplugins.com/plugins/view/169.

Disabling it allowed me to convert a replay, I wasn't sure at first that it had actually completed and I pressed the button again resulting in another crash. But trying again later made it work and I was able to jump in the replay. 
It was a bit janky but usable for its purpose.

**Comment by Al12rs** [comment]
Any clue on why the two plugins would be incompatible and if something can be done to fix it so that both plugins can be used without problems?

**Comment by Atomus48** [comment]
You are righte the "true ball hight indicator" plugin crashes the game when converting. I don't know why it happens i only know that it's not the fault of the JumpInReplay plugin because the dmp file didn't give me any information. The only fix right now is to disabel the "true ball hight indicator" plugin to use JumpInReplay.
