### ISSUE TITLE
Ball is not moving smoothly

### ISSUE THREAD

**Issue by valaram** [Atomus48/JumpInReplay#2]
Hi,
Great plugin by the way. It taken some time to found, how to run it. But the plugin is working great. Only thing is while training through your plugin. ball is flickering. car flicker is not much of an issue. as i generally focused on ball. Is there any way to make ball movement much smoother.

**Comment by Atomus48** [comment]
I'm aware of this problem. if you want it to move smother you have to reduce the Conversion Resolution (in the bakkesmod window (F2)), but this will slow down the time it takes to convert the replay.
