### ISSUE TITLE
Converting Marked Portions of Replays Instead of the Entire Replay

### ISSUE THREAD

**Issue by valaram** [Atomus48/JumpInReplay#4]
Hi,
Is there any way to only convert replays that have a marker, with a range specified by the user (such as 15 seconds before the marker)? Usually, when I make a mistake in a game, I add a marker for the replay. But to just practice that part, I have to convert the whole replay instead of just the marked part.

Also, is there any way to change the resolution to less than 1 so that the ball movement can be much smoother?

**Comment by Atomus48** [comment]
Both things you mentioned are currently not possible, I will release a patch in a week or so to make it possible to set the resolution to less than 1. I will try to implement the idea with the markers, i don't know if i can get it to work, if not the patch will just be the resolution.

**Comment by Atomus48** [comment]
new github commit now has this feature, will probably be on bakkesplugins soon.

**Comment by valaram** [comment]
thank you very much :)
