### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by valaram** [Atomus48/JumpInReplay#5]
Hey there,

I just wanted to drop you a quick message to say thanks for including the keyframe feature in JumpInReplay. It's seriously been a game-changer for me, and I've been able to convert replays in no time at all. In fact, I've gone from being a D3 to a C2 player.

![image](https://user-images.githubusercontent.com/32789365/224350087-8a650959-0218-4450-966e-0b7b0158436b.png)

Anyway, I did have a feature request I wanted to ask about. Do you think it would be possible to add a feature that would let me convert all my replays and save them as a list? It would be amazing if I could save this list so I could play the replays even after restarting the game, without having to convert them again. I love using your plugin daily, but sometimes it can be a bit of a hassle to convert each replay individually.

Oh, and there's one little bug I wanted to mention. When I have multiple keyframes, the game progress bar does jump to the next keyframe, but the car doesn't actually move. To get it working, I have to hit the left arrow key every time it jumps to the next keyframe.

Thanks for your time and all your hard work on JumpInReplay!

**Comment by Atomus48** [comment]
I think i will add the saving converted replays feature at some point in the future, but i don't really have alot of time to work on the plugin right now
