### ISSUE TITLE
Crash shortly after opening saved replay

### ISSUE THREAD

**Issue by Speooo** [Atomus48/JumpInReplay#8]
Pressing "Open Saved Replay" opens up the replay, and a second after the kickoff, the game completely freezes and subsequently crashes to desktop without any error. 

At first I assumed other plugins are causing issues so I disabled every other plugin, but the issue persists. Any advice?

**Comment by Atomus48** [comment]
Hello I have i few questions,
have you tried not pressing "Open saved Replay", "convert replay" will open the replay atomaticly when it finished converting
is this crash repeatable with every replay?
what plugin version are you using (newest on bakkesplugins)?

**Comment by jolive1993** [comment]
Having this same issue with everything latest.
[[0103.08] ScriptWarning ScriptWarni.txt](https://github.com/Atomus48/JumpInReplay/files/14314762/0103.08.ScriptWarning.ScriptWarni.txt)
